# Generated by Django 5.2.10 on 2026-02-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
